package performance.parser;

/** A token generated by some {@link Lexer} */
public interface Token<T> {
	/** @return the token type */
    T getType();
	/** @return the text of the token */
	CharSequence getText();
}
